---
 - hosts: elk
   become: true
   tasks:
     - name: set vm.max_map_count to 262144 in sysctl
       sysctl: name={{ item.key }} value={{ item.value }}
       with_items:
         - { key: "vm.max_map_count", value: "262144" }
     - name: Install docker.io
       apt:
         update_cache: yes  
         name: docker.io
         state: present

     - name: Install pyhton3
       apt:
         name: python3-pip
         state: present

     - name: install docker
       pip:
          name: docker
          state: present

     - name: downlaod and launch docker web container
       docker_container:
           name: elk
           image: sebp/elk:761
           state: started
           restart_policy: always
           published_ports: 5601:5601,9200:9200,5044:5044
              
